version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hospital-postgres
    restart: always
    environment:
      POSTGRES_DB: HospitalSystemDb
      POSTGRES_USER: hospitaluser
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    build:
      context: .
      dockerfile: HospitalSystem/Dockerfile
    container_name: hospital-backend
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=HospitalSystemDb;Username=hospitaluser;Password=strongpassword
    ports:
      - "5272:8080"
      
  frontend:
    build:
      context: ./hospital-frontend
      dockerfile: Dockerfile
    container_name: hospital-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data: