version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hospital-postgres
    restart: always
    environment:
      POSTGRES_DB: HospitalSystemDb
      POSTGRES_USER: hospitaluser
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: HospitalSystem/Dockerfile
    container_name: hospital-backend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5272:5272"

  frontend:
    build:
      context: ./hospital-frontend
      dockerfile: Dockerfile
    container_name: hospital-frontend
    depends_on:
      - backend
    ports:
         - "5173:5173"
volumes:
  postgres_data:
