CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Department" text NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

CREATE TABLE "Patients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "PasswordHash" character varying(50) NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Doctors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DepartmentId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Doctors_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Doctors_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Appointments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Status" text NOT NULL,
    "TimeOfAppointment" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByTheFrontDeskId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Appointments_Users_CreatedByTheFrontDeskId" FOREIGN KEY ("CreatedByTheFrontDeskId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Appointments_CreatedByTheFrontDeskId" ON "Appointments" ("CreatedByTheFrontDeskId");

CREATE INDEX "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");

CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");

CREATE UNIQUE INDEX "IX_Departments_Department" ON "Departments" ("Department");

CREATE INDEX "IX_Doctors_DepartmentId" ON "Doctors" ("DepartmentId");

CREATE UNIQUE INDEX "IX_Doctors_UserId" ON "Doctors" ("UserId");

CREATE UNIQUE INDEX "IX_Users_Name" ON "Users" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260106090316_InitialCreate', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ALTER COLUMN "PasswordHash" TYPE character varying(256);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260106133536_IncreasePasswordHashLength', '8.0.8');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260106163944_.', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Appointments" ADD "CancellationReason" character varying(500) NOT NULL DEFAULT '';

ALTER TABLE "Appointments" ADD "CancelledAt" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260118152915_AddCancellationReasonToAppointment', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Doctors" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Departments" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260124105904_CheckSync', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE UNIQUE INDEX "IX_Patients_PhoneNumber" ON "Patients" ("PhoneNumber");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260215170408_AddPhoneNumberUniqueConstraint', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Appointments" ALTER COLUMN "CancellationReason" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260215172700_MakeCancellationFieldsNullable', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE "CalendarEntity" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DoctorId" integer NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CalendarEntity" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CalendarEntity_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_CalendarEntity_DoctorId" ON "CalendarEntity" ("DoctorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216080436_FixDoctorCalendarRelationship', '8.0.8');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216193104_UpdateDoctorScheduleModel', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "CalendarEntity" DROP CONSTRAINT "FK_CalendarEntity_Doctors_DoctorId";

ALTER TABLE "CalendarEntity" DROP CONSTRAINT "PK_CalendarEntity";

ALTER TABLE "CalendarEntity" RENAME TO "Calendars";

ALTER INDEX "IX_CalendarEntity_DoctorId" RENAME TO "IX_Calendars_DoctorId";

ALTER TABLE "Calendars" ADD CONSTRAINT "PK_Calendars" PRIMARY KEY ("Id");

ALTER TABLE "Calendars" ADD CONSTRAINT "FK_Calendars_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216193953_AddCalendarScheduleSupport', '8.0.8');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217143525_AddCalendarScheduleS', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Calendars" ADD "SlotDurationMin" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260218113657_CustomAppointmentDuration', '8.0.8');

COMMIT;

