name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/hospital-backend/hospital-backend

          # pull latest image
          docker pull kstkaan/hospital-backend:latest

          # stop + remove the old backend container 
          docker-compose stop backend || true
          docker-compose rm -f backend || true

          # recreate using the new image
          docker-compose up -d backend

          # pull latest image
          docker pull kstkaan/hospital-frontend:latest

          # stop + remove the old frontend container 
          docker-compose stop frontend || true
          docker-compose rm -f frontend || true

          # recreate using the new image
          docker-compose up -d frontend




