name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -f HospitalSystem/Dockerfile -t kstkaan/hospital-backend:latest .

      - name: Push backend image
        run: docker push kstkaan/hospital-backend:latest


      - name: Build frontend image
        run: docker build -t kstkaan/hospital-frontend:latest ./hospital-frontend

      - name: Push frontend image
        run: docker push kstkaan/hospital-frontend:latest