name: Docker Image CI

on:
  workflow_run:
   workflows: [".NET"]
   types:
    - completed


jobs:
  docker:
    if: ${{github.event.workflow_run.conclusion=='success'}}
    runs-on: ubuntu-latest
 
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: |
          docker build -f HospitalSystem/Dockerfile \
            -t kstkaan/hospital-backend:latest \
            -t kstkaan/hospital-backend:${{ github.sha }} .

      - name: Push backend image
        run: |
          docker push kstkaan/hospital-backend:latest
          docker push kstkaan/hospital-backend:${{ github.sha }}

      - name: Build frontend image
        run: |
          docker build \
            -t kstkaan/hospital-frontend:latest \
            -t kstkaan/hospital-frontend:${{ github.sha }} \
            ./hospital-frontend

      - name: Push frontend image
        run: |
          docker push kstkaan/hospital-frontend:latest
          docker push kstkaan/hospital-frontend:${{ github.sha }}