name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: docker build ./HospitalSystem/ -t kstkaan/githubactions:latest

      - name: push to docker hub
        run: docker push kstkaan/githubactions:latest